In [7]:
import numpy as np
filename = 'jump00.txt'
data = np.loadtxt(filename, delimiter=',', skiprows=2, dtype = str)
print(data)

ValueError: the number of columns changed from 2 to 1 at row 5; use `usecols` to select a subset and avoid this error

In [9]:
file = open('jump00.txt', 'r')
lines = file.readlines()
array = []
for line in lines:
    element = line.strip().split()
    array.append(element)

In [18]:
len(array[9:])
array1 = array[9:-2]
array1

[['[0.00000,',
  '0.00000,',
  '0.34269,',
  '-0.01876,',
  '0.08498,',
  '-0.03986,',
  '0.99541,',
  '-0.02538,',
  '0.34689,',
  '-1.92098,',
  '-0.04037,',
  '-0.23181,',
  '-1.54735,',
  '-0.00989,',
  '0.90845,',
  '-1.64901,',
  '0.10557,',
  '1.36464,',
  '-1.86798,',
  '0.40491,',
  '0.12803,',
  '-0.23632,',
  '0.54193,',
  '-0.14166,',
  '-0.18809,',
  '-0.26836,',
  '0.13065,',
  '-0.33907,',
  '-0.36402,',
  '-0.10507,',
  '-0.27741,',
  '1.42826,',
  '-0.08921,',
  '0.13557,',
  '0.54237,',
  '0.91287,',
  '-0.44563,',
  '0.57940,',
  '5.43760,',
  '-3.03241,',
  '-0.34933,',
  '2.79530,',
  '-0.80202,',
  '0.18216,',
  '1.73311,',
  '-0.15149,',
  '-0.70269,',
  '0.03531,',
  '-4.08587,',
  '-1.25209,',
  '0.13632,',
  '0.01927,',
  '-0.59959,',
  '-0.09766,',
  '-0.58667,',
  '-0.55521,',
  '0.06207,',
  '0.10474,',
  '0.85001,',
  '-0.24013,',
  '0.59320],'],
 ['[0.04684,',
  '-0.00669,',
  '0.33932,',
  '-0.00987,',
  '0.09946,',
  '-0.04821,',
  '0.99382,',
  '-0.006

In [19]:
array

[['{'],
 ['"LoopMode":', '"Wrap",'],
 ['"FrameDuration":', '0.033,'],
 ['"EnableCycleOffsetPosition":', 'true,'],
 ['"EnableCycleOffsetRotation":', 'true,'],
 ['"MotionWeight":', '6.0,'],
 [],
 ['"Frames":'],
 ['['],
 ['[0.00000,',
  '0.00000,',
  '0.34269,',
  '-0.01876,',
  '0.08498,',
  '-0.03986,',
  '0.99541,',
  '-0.02538,',
  '0.34689,',
  '-1.92098,',
  '-0.04037,',
  '-0.23181,',
  '-1.54735,',
  '-0.00989,',
  '0.90845,',
  '-1.64901,',
  '0.10557,',
  '1.36464,',
  '-1.86798,',
  '0.40491,',
  '0.12803,',
  '-0.23632,',
  '0.54193,',
  '-0.14166,',
  '-0.18809,',
  '-0.26836,',
  '0.13065,',
  '-0.33907,',
  '-0.36402,',
  '-0.10507,',
  '-0.27741,',
  '1.42826,',
  '-0.08921,',
  '0.13557,',
  '0.54237,',
  '0.91287,',
  '-0.44563,',
  '0.57940,',
  '5.43760,',
  '-3.03241,',
  '-0.34933,',
  '2.79530,',
  '-0.80202,',
  '0.18216,',
  '1.73311,',
  '-0.15149,',
  '-0.70269,',
  '0.03531,',
  '-4.08587,',
  '-1.25209,',
  '0.13632,',
  '0.01927,',
  '-0.59959,',
  '-0.09766,

In [20]:
array1[0]

['[0.00000,',
 '0.00000,',
 '0.34269,',
 '-0.01876,',
 '0.08498,',
 '-0.03986,',
 '0.99541,',
 '-0.02538,',
 '0.34689,',
 '-1.92098,',
 '-0.04037,',
 '-0.23181,',
 '-1.54735,',
 '-0.00989,',
 '0.90845,',
 '-1.64901,',
 '0.10557,',
 '1.36464,',
 '-1.86798,',
 '0.40491,',
 '0.12803,',
 '-0.23632,',
 '0.54193,',
 '-0.14166,',
 '-0.18809,',
 '-0.26836,',
 '0.13065,',
 '-0.33907,',
 '-0.36402,',
 '-0.10507,',
 '-0.27741,',
 '1.42826,',
 '-0.08921,',
 '0.13557,',
 '0.54237,',
 '0.91287,',
 '-0.44563,',
 '0.57940,',
 '5.43760,',
 '-3.03241,',
 '-0.34933,',
 '2.79530,',
 '-0.80202,',
 '0.18216,',
 '1.73311,',
 '-0.15149,',
 '-0.70269,',
 '0.03531,',
 '-4.08587,',
 '-1.25209,',
 '0.13632,',
 '0.01927,',
 '-0.59959,',
 '-0.09766,',
 '-0.58667,',
 '-0.55521,',
 '0.06207,',
 '0.10474,',
 '0.85001,',
 '-0.24013,',
 '0.59320],']

In [22]:
import numpy as np
f = open(r"jump00.txt")
line = f.readline()
data_list = []
while line:
    num = list(map(float,line.split()))
    data_list.append(num)
    line = f.readline()
f.close()
data_array = np.array(data_list)


ValueError: could not convert string to float: '[0.00000,'

In [2]:
from log_data import ref_data
ref_data
ref_data.shape

(53, 61)

In [3]:
import torch

def quat_rotate_inverse(q, v):
    shape = q.shape
    q_w = q[:, -1]
    q_vec = q[:, :3]
    
    a = v * (2.0 * q_w ** 2 - 1.0).unsqueeze(-1)
    b = torch.cross(q_vec, v, dim=-1) * q_w.unsqueeze(-1) * 2.0
    c = q_vec * torch.bmm(q_vec.view(shape[0], 1, 3), v.view(shape[0], 3, 1)).squeeze(-1) * 2.0
    
    return a - b + c

# Example usage
q = torch.tensor([
    [0.0, 0.0, 0.0, 1.0],     # Identity quaternion (no rotation)
    [0.6, 0.0, 0.6, 0.0] # 90-degree rotation around the y-axis
])
v = torch.tensor([
    [1.0, 0.0, 0.0], # Vector along the x-axis
    [0.0, 1.0, 0.0]  # Vector along the y-axis
])

rotated_v = quat_rotate_inverse(q, v)
print(rotated_v)

tensor([[ 1.,  0.,  0.],
        [ 0., -1.,  0.]])


In [4]:
import torch

In [5]:
a = torch.tensor([1.0, 2.0, 3.0, 4.0])
b = torch.tensor([2.0, 2.0, 2.0, 4.0])
a * b

tensor([ 2.,  4.,  6., 16.])

In [6]:
c = torch.tensor([8.0, 8.0, 8.0, 8.0])
(a*b)/c

tensor([0.2500, 0.5000, 0.7500, 2.0000])

In [3]:
condi = False
a = 0 if condi else 1.0
a

1.0